<?php
function widget_selection($options){
	/*
	created 2011-04-10 by SF; example as follows:
	(minimum variables)
	$selWOutput=widget_selection(array(
		'filterNode' => 'invoiceStatuses',
		'optionLabel' => 'invoice status',
		'varGroup' => 'invoices',
		'anchorLabel' => 'Pay status',
		'anchorImgPath' => '/images/assets/i-payment.jpg',
		'selOptions' => array(
			1=>'Unpaid',
			2=>'Partially Paid',
			3=>'Paid',
		)
	));

	todo on this
	------------
		DONE	abstract this so we can have multiple
		change the icon option with label capability too - CSS it
		add a few notes
		make it look good
		DONE	bring physical output up to top
		need a globally standard text description of 
			1. filtered by this criteria or not
			2. list of selected statuses, e.g. "Including paid, partially paid, and unpaid [invoices]"
		make it "glow" when a partial set of filters is present (by a class)
		save into snippets

	*/
	global $widget_selection, $fl, $ln, $qr, $fromHdrBugs, $developerEmail;
	extract($options);
	ob_start();
	if(count($_SESSION['userSettings']))
	foreach($_SESSION['userSettings'] as $n=>$v){
		if(!stristr($n,$filterNode))continue;
		if($v /* must have at least one "status" requested */)$filterSelWSet=true;
	}
	if(!$filterSelWSet || strtolower($GLOBALS['selWRefreshFilter'])==strtolower($filterNode)){
		//get db filters
		$o=q("SELECT varkey, varvalue FROM bais_settings WHERE UserName='".$_SESSION['admin']['userName']."' AND vargroup='$varGroup' AND varnode='$filterNode'", O_COL_ASSOC);
		//reset if out of synch
		if(count($selOptions)!==count($o)){
			q("DELETE FROM bais_settings WHERE UserName='".$_SESSION['admin']['userName']."' AND vargroup='$varGroup' AND varnode='$filterNode'");
			foreach($_SESSION['userSettings'] as $n=>$v){
				if(stristr($n,'$filterNode'))unset($_SESSION['userSettings'][$n]);
			}
			foreach($selOptions as $n=>$v){
				q("REPLACE INTO bais_settings SET UserName='".$_SESSION['admin']['userName']."', 
				vargroup='$varGroup', varnode='$filterNode', varkey='$n', varvalue=1");
				$_SESSION['userSettings'][$filterNode.':'.$n]=1;
			}
		}else if($o){
			foreach($o as $n=>$v)$_SESSION['userSettings'][$filterNode.':'.$n]=$v;
		}
	}
	//now unfortunately we must loop through one more time to get selected statuses count
	if(count($_SESSION['userSettings']))
	foreach($_SESSION['userSettings'] as $n=>$v){
		if(!stristr($n,$filterNode))continue;
		if($v)$optionsCount++;
	}
	
	//handle incoming request - overwrite both db and session settings from above
	if($GLOBALS['filterSelW'] && $GLOBALS['targetFilterNode']==$filterNode){
		if($GLOBALS['current']==1 && $optionsCount<2)error_alert('You must have at least one '.$optionLabel.' selected');
		$_SESSION['userSettings'][$filterNode.':'.$GLOBALS['filterSelW']]=($GLOBALS['current'] ? 0 : 1);
		q("REPLACE INTO bais_settings SET UserName='".$_SESSION['admin']['userName']."', 
		vargroup='$varGroup', varnode='$filterNode', varkey='".$GLOBALS['filterSelW']."', varvalue=".($GLOBALS['current'] ? 0 : 1));
	}
	//and loop AGAIN.. this codeblock can certainly be cleaned up!!!
	foreach($_SESSION['userSettings'] as $n=>$v){
		if(!$v || !stristr($n,$filterNode))continue;
		//global settings
		$widget_selection[$filterNode]['statusSet'][]=end(explode(':',$n));
	}
	$widget_selection['widgets']++;
	?>
	<!-- selection widget generated by <?php __FILE__?>; <?php echo date('Y-m-d g:iA');?> -->
	<style type="text/css">
	#selWList<?php echo $widget_selection['widgets'];?>{
		position:relative;
		cursor:pointer;
		}
	#selWList_head_<?php echo $filterNode?>{
		}
	#selWList_sub_<?php echo $filterNode?>{
		position:absolute;
		left:0px;
		top:35px;
		width:205px;
		background-color:#ccc;
		}
	.selWListopt{
		clear:both;
		padding:1px 7px;
		}
	#selWList<?php echo $widget_selection['widgets'];?> .on{
		background-color:darkblue;
		color:white;
		}
	/*
	#selWList_sub_<?php echo $filterNode?>{
		visibility:hidden;
		}
	*/
	.ck{
		width:20px;
		text-align:center;
		}
	
	
	.age{
		float:left;width:3.0em;
		}
	</style>
	<script language="javascript" type="text/javascript">
	<?php 
	global $widget_selection_js_function;
	if(!$widget_selection_js_function){ $widget_selection_js_function=true;
	?>
	function selWidget(o,a,f,s){
		switch(a){
			case 0:
				o.className='selWListopt';
			break;
			case 1:
				o.className='selWListopt on';
			break;
			case 2:
				window.open('/gf5/console/resources/bais_01_exe.php?mode=refreshComponent&component=<?php echo $GLOBALS['datasetComponent'];?>&targetFilterNode='+f+'&filterSelW='+o.id.replace('selWListoption_'+f+'_','')+'&current='+s+'&componentFile=<?php echo $GLOBALS['datasetReferenceFile']?>&componentKey=<?php echo $GLOBALS['datasetReferenceFileKey']?>','w2');
			break;
			case 3:
				g('selWList_sub_'+f).style.visibility='hidden';
			break;
		}
	}
	function showoptions(n){
		eval("document.getElementById('selWList_sub_'+n).style.visibility=(selWon_"+n+"?'visible':'hidden');");
		setTimeout('showoptions(\''+n+'\')',100);
	}
	<?php } ?>
	var selWon_<?php echo $filterNode?>=false;
	setTimeout('showoptions(\'<?php echo $filterNode?>\')',1000);
	</script>
	<div id="selWList<?php echo $widget_selection['widgets'];?>" class="frb">
		<div id="selWList_head_<?php echo $filterNode?>" onClick="selWidget(this,3,'<?php echo $filterNode?>');" onMouseOver="selWon_<?php echo $filterNode;?>=true;" onMouseOut="selWon_<?php echo $filterNode;?>=false;">
		<div><img src="<?php echo $anchorImgPath?>" alt="<?php echo $anchorLabel?>" /> <?php echo $anchorLabel?></div>
		</div>
		<div id="selWList_sub_<?php echo $filterNode?>" style="visibility:<?php echo 'hidden';?>;" onmouseover="selWon_<?php echo $filterNode;?>=true;" onMouseOut="selWon_<?php echo $filterNode;?>=false;">
			<?php
			foreach($selOptions as $n=>$v){
				?><div id="selWListoption_<?php echo $filterNode?>_<?php echo $n?>" class="selWListopt" onMouseOver="selWidget(this,1,'<?php echo $filterNode?>');" onMouseOut="selWidget(this,0,'<?php echo $filterNode?>');" onClick="selWidget(this,2,'<?php echo $filterNode?>',<?php echo $_SESSION['userSettings'][$filterNode.':'.$n] ? 1 : 0;?>);" title="<?php echo $_SESSION['userSettings'][$filterNode.':'.$n] ? 'Hide' : 'Show'?> this category of invoices">
				<div class="frb"><?php echo $selWOptionCount[$n]?></div>
				<div id="selWck_<?php echo $n?>" class="flb ck"><?php 
				if($_SESSION['userSettings'][$filterNode.':'.$n]){
					?><img src="/images/i/check1.png" width="16" height="16" alt="x" /><?php
				}else{
					echo '&nbsp;';
				}?></div>
				<div class="" id="selWListoption_<?php echo $filterNode?>_<?php echo $n?>_name"><?php echo $v?></div>
				</div><?php
			}
			?>
		</div>
	</div>
	<?php
	$selWOutput=ob_get_contents();
	ob_end_clean();
	return $selWOutput;
}
?>